### PR TITLE
IUM-1991 updated dependencies

### PR DESCRIPTION
**Pull request by TimLawton-Auth0**
### Description

Updated dependencies that were flagged by Github Dependabot. Some of these update address security issues such as prototype pollution.

### References

IUM-1991: https://auth0team.atlassian.net/browse/IUM-1991?atlOrigin=eyJpIjoiOTI3NTI1NDE2NzE3NDRkMmFkMjAyNWExZjgxNDlkZjciLCJwIjoiaiJ9

ld-adap open dependencies addressed: https://github.com/auth0/ad-ldap-connector/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies

#### Dependency Differences
async: https://github.com/caolan/async/compare/0.2.10...v2.6.4

ini: https://github.com/npm/ini/compare/v1.3.5...v1.3.8

path-parse: https://github.com/jbgutierrez/path-parse/commits/v1.0.7

normalize-url: https://github.com/sindresorhus/normalize-url/commits

glob-parent: https://github.com/gulpjs/glob-parent/compare/v5.1.1...v5.1.2

lodash: https://github.com/lodash/lodash/compare/4.17.20...4.17.21

hosted-git-info: https://github.com/npm/hosted-git-info/compare/v2.8.8...v2.8.9

y18n: https://github.com/yargs/y18n/commits

#### Unit Test Result Output
➜  ad-ldap-connector git:(IUM-1991-update-auth0/ad-ldap-connector-dependencies) npm test

> ad-ldap-connector@6.1.5 test
> NODE_TLS_REJECT_UNAUTHORIZED=0 mocha --timeout 50000 --reporter spec --exit

Connecting to websocket...
Connecting to undefined.

  Connection to server with empty subject
(node:18292) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
    ✓ should connect when using connector's server identity verification

  crypto deciphering
    ✓ should work for v1 encryption
    ✓ should work for v2 encryption (49ms)
    ✓ encryption/decryption should work for v2 encryption (77ms)

  memberOf walker
    ✓ should contain the inmediate parent
    ✓ should contain the grand parents
    ✓ should contain the great grand parents

  objectsid parsing
    ✓ should work
    ✓ should return undefined when is not a buffer
    ✓ should return undefined when buffer is empty

  users
    - should be able to query by name
    - should be able to query by name (specifying limit)
    - should returns all users if search parameter is empty
    - should be able to validate multiple simultaneous requests
    validate with username and password
      - should include groups
      - should include basic attributes
    validate with username and password and groups with extended properties list
      - should include groups
      - should include basic attributes
    validate with wrong password
      - should fail with WrongPassword
      - should include groups
      - should include basic attributes
    validate with wrong username
      - should fail with WrongUsername
      - should include the username
    change password
      - should include groups
      - should include basic attributes
    change password that doesn't meet complexity
      - should contain error
      - should include groups
      - should include basic attributes
    listing groups from the AD server
      - should return the groups
    listing users with groups from the AD server when the cache is disabled
      - should return the groups
    listing groups from AD server with extended properties list
      - should return the groups with extended properties

  ws_validator
    ✓ authenticate_connector
Connected to websocket
Socket error: Error: test
websocket deconnected. reconnecting
    ✓ terminate socket on error (822ms)
Connecting to websocket...
Connecting to undefined.

  12 passing (999ms)
  21 pending

-------

#### Currently working on running system tests against Vivaldi

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by bernardwolff** [comment]
Does it make sense to be adding new dependencies to package.json? I think these are transitive dependencies (dependencies of packages that are already in package.json). Newer versions of npm have an `overrides` feature but upgrading npm might be outside the scope of this story. You can set the versions of these transitive dependencies in the package-lock.json file as dependabot was suggesting.

**Comment by TimLawton-Auth0** [comment]
@bernardwolff, I used `npm install <dependency>@<version>. Some of these dependency upgrades are due to added/upgraded dependencies in other files. What would be a better way to upgrade the dependencies for only package-lock.json? Should I just use `npm i <dependency>@<version> --package-lock-only` and update the package.json manually by hand?

**Comment by bernardwolff** [comment]
I think the best approach would be to upgrade the top level dependencies that depend on the packages that dependabot is saying to upgrade. For example, dependabot is saying to upgrade glob-parent from 5.1.1 to 5.1.2. If we run `npm ls -a glob-parent`, we can see that it's a dependency of mocha. So we can upgrade mocha to a newer 8.x version (we're currently on 8.2.1, but the newest 8.x version is 8.4.0). This should be safe since it's still the same major version (8). After upgrading mocha, you can check what version of glob-parent it installed again with `npm ls -a glob-parent`, and you'll see it is 5.1.2. A similar process can be performed with the other packages.

**Comment by TimLawton-Auth0** [comment]
What would be the best way to upgrade without npm install? This imports other dependencies into the package.json

**Comment by bernardwolff** [comment]
I tried `npm install --save-dev mocha@8.4.0` and the only change to package.json was the line for mocha. Are you seeing something different? I agree that updating the lock file by hand is risky. That's why I suggested the second approach.

**Comment by bernardwolff** [comment]
Another approach might be to cherry-pick the commits off the dependabot PRs. Maybe that's best as it limits the number of packages getting upgraded to just the ones necessary for now.

**Comment by TimLawton-Auth0** [comment]
> 

I followed these steps and this line was additionally added to package.json `"save-dev": "0.0.1-security",` is this okay?

**Comment by TimLawton-Auth0** [comment]
Reverted to clean state

**Comment by TimLawton-Auth0** [comment]
Successfully Octopus merged Dependabot PRs. Currently Testing results

**Comment by TimLawton-Auth0** [comment]
Tests complete. No issues found

**Review by vmarceau — CHANGES_REQUESTED** [review]
To release a new version of the connector, please bump the `"version"` tag to `"6.1.6"` at the top of the `package.json` and `package-lock.json` files. Also add an entry in the `CHANGELOG.md` file. Thanks!

**Comment by TimLawton-Auth0** [comment]
@vmarceau made changes

**Review by bernardwolff — APPROVED** [review]

**Comment by bernardwolff** [comment]
I'm assuming you have concluded that there are no breaking changes that affect the code in this repo for the `async` dependency.

**Comment by TimLawton-Auth0** [comment]
@bernardwolff I was unable to find any breaking changes

**Pull request merged**
